language: python
python:
- '3.6'
- 3.6-dev
env:
- PIPENV_IGNORE_VIRTUALENVS=1
install:
- pip install pipenv
- pipenv install --dev
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- pipenv run black --check .
- pipenv run isort --check-only
- find . -iname "*.py" | xargs pipenv run pylint
- pipenv run coverage run --source=faker_microservice tests.py
- pipenv run coverage xml
- pip install faker-microservice
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
deploy:
  provider: pypi
  user: craiga
  password:
    secure: rPszZ864doyaNOcUPUISBlfKIx6+k7PGzrRU3llqYBxlzVMa/T4y15kV4imO0oWh7kLhNZgy8paxQfM+UsbSHWOUv70fCkDDYIWgn+EDrQZtbr+YS8Xuc2buzRfRYa+F222gat5DuyDY9bhdRvB7v+BvE4YyHJAYmwXfVfIMOnhuIBkdHqAfQnMk3dN7eZd6DLxxIV3yDE0MD+ltDSLJwxYfZoze4jZNsssccve1l82by8u/qwasmEZMNl6Fy34RPY/1dXccNSdlxiWrv72Sxnu0w198+GnEa/EwXmHn+bq9Epd0LabURmGNDCINdjVvqm9zLiVGECpz4h95KnoNVZ0BOKMOZRzVuYPPrbFikO0e5BrgJ8V3amQkeYSVxVsRpGKqU0cAHa3EwLmL0a3J6astm1KtkckE50lp/ak/luoU2kVo39Nm3/RZkVLNoaJxORbNHtWWBD7qsADjL79CuRrk8NDdZCsIA5aXIP4RGYCb9YltBtFyfQQ7hobd9cVOnbWlIQfVRRjVt0colhAqOPm2k2Vh/tT0Ik+dSqlMSDV/wjvSFpJG09zXx9CL/LsVCD093uf/CZbnc/zWYOYxiqeuMGABjl5cgYFY6SxAzOPv1luGLAqasNn9tB9LNHFfJv8js86lL7ibtMTZ+6362C0sTrZThkFh45c0bV5Vd4o=
  skip_existing: true
  on:
    tags: true
