language: python
python:
- '3.6'
- 3.6-dev
install:
- pip install pipenv
- pipenv install --dev
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- pipenv run black --check .
- pipenv run isort --check-only
- find . -iname "*.py" | xargs pipenv run pylint
- pipenv run coverage run --source=faker_microservice tests.py
- pipenv run coverage xml
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
deploy:
  provider: pypi
  user: craiga
  password:
    secure: SdbxXKYQxfg4eAcSZejTyyrydHAm73pKnUO1CVJYc1jdlx7oTGl6iEOWp+fYW5YqdJGwCe72N0R/WJCYN86Trck4sCRfWjiCfUh+W9aqovD/j2vvp+qIVjfRHqYTOM63O7KIQyaNp6JNEqx5BvSxpjISu1kaOs4lGwGHVDMArodKdHv0mAUrsUM3+jfDOuzkJSE54plP1NEyxJ/jxkKB7Mk8wkSOdNZO9Fvkfy4lKYi+D936ALTPGKEcl8C1GK4jxLx8oZokJMA0fxJ7LPA5zFVeRF6rKMlvZIq1JDOy4x7yFjzYpap3Z39SEVYcAoLwI1f7YUTJOJacNEy6K/rGl9TbFqsVmbvj3XtdMgFdCVn/oTM7H+FESOMwoj5Mf8BBMfiwHXG+kdnnKk7RLZTBG7ne347Vx08ZSAo/RT9NsMMlfniYQYsWx7F27QEGf4p/VxPWEJ9ei36wr/C7k2+0FlNqbz52s2qgdd0VxLrcpcJd1cHmn7Y2wPH6BwUmbSZwEprPcQZEZ7Y6cAOp6KuuRksQsg0Iv8I4oA9ACE/++CMci1hRG1UMOX95/z9X1Oi6qQ2r6yAUg4Rh8xyQvjoliK/dUfIcyr0VVS5cGqwQKJHo1H/2eBlHGV4xt6CGn2EqZoK9jCPfubn1isXIVufeQ0GauP4hfq0EJajsso/qZUw=
  skip_existing: true
  on:
    tags: true
