language: python
python:
- '3.6'
- 3.6-dev
install:
- pip install pipenv
- pipenv install --dev
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- pipenv run black --check .
- pipenv run isort --check-only
- find . -iname "*.py" | xargs pipenv run pylint
- pipenv run coverage run --source=faker_microservice tests.py
- pipenv run coverage xml
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
deploy:
  provider: pypi
  user: craiga
  password:
    secure: CQRlrLRLv1FfDmMZzfTFIGQo+iJh/kW7LAcdPVyBDJsVykt8QESZ0u3VYXws10lzqEOnXbkfGmSAuPmfM+cYqoe6ztgnLovR/mUkR5S+7G+689cBDT2b2VmR3uPHN5wkNEkAWVRUmSbi+v6NTz57oJa02AISHa6z1QtAdfchUvtKe2iDAoY8rNkLZOMo+R6kO85f4BJEOiwZu4t2NCvBywVC+G2SLs4awWje7UhR+KmRWrHHVHFHZ8CE54ApG9Zf5C+rBNcNIu+T7U74bOt0YmVT1EUe+iozrFDoTpB0e23MNFS0yXqKZ7qFqNjUfTp2YfqWGRa4znlWJO0ly0no9UbX9QuTAIs2iPHrlliFJjs/gNoAlowKnn7TRpwfQFXsTL/EkOMeXtmrsdGXzAOmc8yFPeMlB/n9s4/4ODOlS85oMXddhgdvVThygc7hZslLmuEv1yrOrwlb4bQ7DtRdnBCOR2656pR9h0HDLZYQQUJuOF/YI8oyjeOdnjnRx04uHeswXwT6vj9w1X9dhym4WVaI2d124BFgbFz0RdWc1UYiE3f+asErjgFrJuQd073N3JoUZ57FBkRXvlTs690loXQSJ6ob9pXf1xotxgzx7vbkd4m0AHFX8+NeSxeGuMAiUbDQfZXM241XB/hUBt2MjxmBgVLthNbHP04cWRYdSd4=
  skip_existing: true
  on:
    tags: true
